services:
  mariadb:
    image: mariadb:lts
    volumes:
      - spring_security_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: spring_security_learning

volumes:
  spring_security_data: